openapi: 3.0.0
servers:
  - url: http://projom.se/api
info:
  title: Projom.se Pokemon API documentation
  version: 1.0.0
tags:
  - name: Pokemon
    description: Query for your favorite pokemon!
paths:
  /pokemons:
    $ref: "pokemon.yml#/get_list"
  /pokemons/{string}:
    $ref: "pokemon.yml#/get_by_string"
  /pokemon/bosses:
    $ref: "pokemon/boss.yml#/get_boss_list"
  /pokemon/boss/shinies:
    $ref: "pokemon/boss.yml#/get_boss_shiny"
