openapi: 3.0.0
info:
  title: Projom.se Pokemon API documentation
  version: 1.0.0
paths:
  /api/pokemon:
    $ref: "pokemon.yml#/get_list"
  /api/pokemon/{id}:
    $ref: "pokemon.yml#/get_by_id"
  /api/pokemon/{name}:
    $ref: "pokemon.yml#/get_by_name"

