openapi: 3.0.0
servers:
  - url: http://projom.se/api
info:
  title: Projom.se Pokemon API documentation
  version: 1.0.0
tags:
  - name: pokemon
    description: Query for your favorite pokemon!
paths:
  /pokemon:
    $ref: "pokemon.yml#/get_list"
  /pokemon/{id}:
    $ref: "pokemon.yml#/get_by_id"
  /pokemon/{name}:
    $ref: "pokemon.yml#/get_by_name"
